swagger: "2.0"
info:
  description: "日升木业后台接口"
  version: "1.0.0"
  title: "sunup"
tags:
- name: "User"
  description: "用户相关接口"

- name: "Product"
  description: "商品相关接口"
schemes:
- "http"
produces:
- "application/json"
securityDefinitions:
  token:
    type: apiKey
    name: Cookie
    in: header
security:
- token: []
paths:

  /user/register:
    post:
      tags:
        - "User"
      summary : "注册用户"
      operationId: "registerUser"
      parameters:
        - name: "user"
          in:  body
          required: true
          schema:
            $ref: '#/definitions/UserDTO'
      responses:
        200:
          description: "success"
  /user/login:
    post:
      tags:
        - "User"
      summary: "用户登陆"
      operationId: "login"
      parameters:
        - name: "user"
          in:  body
          required: true
          schema:
            $ref: '#/definitions/UserDTO'
            required:
              - name
              - password
      responses:
        200:
          description: "success"
  /user/loginOut:
    get:
      tags:
        - "User"
      summary: "用户登出"
      operationId: "loginOut"
      responses:
        200:
          description: "success"

  /project/labels:
    get:
      tags:
        - "Product"
      summary: "获取标签列表"
      operationId: "getLabels"
      parameters:
        - in: query
          name: "keyword"
          type: string
      responses:
        200:
          description: "success"
          schema:
            $ref: '#/definitions/LabelList'
    post:
      tags:
        - "Product"
      summary: "添加标签"
      operationId: "addLabel"
      parameters:
        - name: "label"
          in:  body
          required: true
          schema:
            $ref: '#/definitions/LabelDTO'
            required:
              - name
      responses:
          200:
            description: "success"
    delete:
      tags:
        - "Product"
      summary: "删除标签"
      operationId: "deletedLable"
      parameters:
        - in: query
          name: "id"
          type: string
          required: true
      responses:
        200:
          description: "success"
    put:
      tags:
        - "Product"
      summary: "修改标签"
      operationId: "modifyLabel"
      parameters:
        - name: "label"
          in:  body
          required: true
          schema:
            $ref: '#/definitions/LabelDTO'
            required:
              - name
              - id
      responses:
        200:
          description: "success"



definitions:

  UserDTO:
    type: object
    properties:
      name:
        type: string
        description: "用户名"
      password:
        type: string
        description: "用户密码"

  LabelList:
    type: array
    items:
      $ref: '#/definitions/LabelDTO'

  LabelDTO:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      labelDeclare:
        type: string

