server:
  port: 8080

spring:
  datasource:
    name: sunup
    url: jdbc:mysql://118.89.182.204:3306/sunup?characterEncoding=utf-8&useSSL=false
    username: sunup
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    servlet:
      multipart:
        max-file-size: 20MB
        max-request-size: 20MB
  mail:
    host: smtp.163.com
    username: jiangmurisheng@163.com
    password: glsl689677
    protocol: smtp
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
    properties.mail.smtp.socketFactory.fallback: false
    properties.mail.smtp.port: 994
    properties.mail.smtp.socketFactory.port: 994
    default-encoding: utf-8
    from: jiangmurisheng@163.com
    to: 582686359@qq.com

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.chainof.sunup.model


#pagehelper分页插件配置
#  pagehelper.helperDialect=mysql
#  pagehelper.reasonable=true
#  pagehelper.supportMethodsArguments=true
#  pagehelper.params=count=countSql

logging:
  level:
    cn.chainof.sunup.common: DEBUG
    cn.chainof.sunup.conf: DEBUG
    cn.chainof.sunup.controller: INFO
    cn.chainof.sunup.mapper: DEBUG
    cn.chainof.sunup.filter: INFO
    cn.chainof.sunup.pojo: INFO
    cn.chainof.sunup.service: DEBUG

#腾讯云COS
qcloud.cos:
  AppId: 1259283245
  SecretId: AKIDsVtCKC5AKEsGWawvDI7gzA8rJVYLjAML
  SecretKey: xf8ML4Wr1vZx5wXr33mFZgX7RdeOsFOG
  BucketName: sevennotes-1259283245
  Region: ap-chengdu
  ImgUrl: https://sevennotes-1259283245.cos.ap-chengdu.myqcloud.com

allowedOrigins: