swagger: "2.0"
info:
  description: "日升木业后台接口"
  version: "1.0.0"
  title: "sunup"
tags:
- name: "User"
  description: "用户相关接口"

- name: "Project"
  description: "项目全局相关接口"

- name: "ProductItem"
  description: "商品分类相关接口"

- name: "File"
  description: "文件相关接口"
schemes:
- "http"
produces:
- "application/json"
securityDefinitions:
  token:
    type: apiKey
    name: Cookie
    in: header
security:
- token: []
paths:

  /user/register:
    post:
      tags:
        - "User"
      summary : "注册用户"
      operationId: "registerUser"
      parameters:
        - name: "user"
          in:  body
          required: true
          schema:
            $ref: '#/definitions/UserDTO'
      responses:
        200:
          description: "success"
  /user/login:
    post:
      tags:
        - "User"
      summary: "用户登陆"
      operationId: "login"
      parameters:
        - name: "user"
          in:  body
          required: true
          schema:
            $ref: '#/definitions/UserDTO'
            required:
              - name
              - password
      responses:
        200:
          description: "success"
  /user/loginOut:
    get:
      tags:
        - "User"
      summary: "用户登出"
      operationId: "loginOut"
      responses:
        200:
          description: "success"

  /project/labels:
    get:
      tags:
        - "Project"
      summary: "获取标签列表"
      operationId: "getLabels"
      parameters:
        - in: query
          name: "keyword"
          type: string
      responses:
        200:
          description: "success"
          schema:
            type: array
            items:
              $ref: '#/definitions/LabelDTO'
    post:
      tags:
        - "Project"
      summary: "添加标签"
      operationId: "addLabel"
      parameters:
        - name: "label"
          in:  body
          required: true
          schema:
            $ref: '#/definitions/LabelDTO'
            required:
              - name
              - labelCode
      responses:
          200:
            description: "success"
    delete:
      tags:
        - "Project"
      summary: "删除标签"
      operationId: "deletedLable"
      parameters:
        - in: query
          name: "id"
          type: string
          required: true
      responses:
        200:
          description: "success"
    put:
      tags:
        - "Project"
      summary: "修改标签"
      operationId: "modifyLabel"
      parameters:
        - name: "label"
          in:  body
          required: true
          schema:
            $ref: '#/definitions/LabelDTO'
            required:
              - name
              - id
      responses:
        200:
          description: "success"

  /project/uploadImg:
    post:
      summary: 上传图片
      description: file：选择文件
      operationId: uploadImg
      tags:
        - "File"
      consumes:
        - "multipart/form-data"
      produces:
        - "application/json"
      parameters:
        - in: formData
          name: file
          type: file
          required: true
      responses:
        '200':
          schema:
            type: string
          description: 返回图片地址

  /project/product/item:
    get:
      tags:
        - "ProductItem"
      summary: "查看分类列表"
      operationId: getItems
      parameters:
        - name: "key"
          in: query
          type: string
          description: "分类关键字，分类名，描述，模糊查询"
      responses:
        '200':
          schema:
            type: array
            items:
              $ref: '#/definitions/ItemDTO'
          description: "分类列表"
    post:
      tags:
        - "ProductItem"
      summary: "增加分类"
      operationId: addItem
      parameters:
        - name: "item"
          in: body
          required: true
          schema:
            $ref: '#/definitions/ItemDTO'
            required:
              - itemName
              - isRoot
      responses:
        '200':
          description: 新增成功
    put:
      tags:
        - "ProductItem"
      summary: "修改分类"
      operationId: modifyItem
      parameters:
        - name: "item"
          in: body
          required: true
          schema:
            $ref: '#/definitions/ItemDTO'
            required:
              - id
              - itemName
              - isRoot
      responses:
        '200':
          description: 修改成功
    delete:
      tags:
        - "ProductItem"
      summary: "删除分类"
      operationId: deletedItem
      parameters:
        - in: query
          name: id
          type: string
          required: true
          description: "分类ID"
      responses:
        200:
          description: "删除成功"
  /project/product/getRootItems:
    get:
      tags:
        - "ProductItem"
      summary: "获取根级分类"
      operationId: getRootItems
      responses:
        200:
          schema:
            type: array
            items:
              $ref: '#/definitions/ItemDTO'
          description: "获取主分类列表"
  /project/product/getItemsByParentId:
    get:
      tags:
        - "ProductItem"
      summary: "根据上级分类获取下级分类列表"
      operationId: getItemsByParentId
      parameters:
        - in: query
          name: parentId
          type: string
          required: true
      responses:
        200:
          schema:
            type: array
            items:
              $ref: '#/definitions/ItemDTO'
          description: "获取分类列表"

definitions:
  UserDTO:
    type: object
    properties:
      name:
        type: string
        description: "用户名"
      password:
        type: string
        description: "用户密码"

  LabelDTO:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      labelCode:
        type: string
      labelDeclare:
        type: string

  ItemDTO:
    type: object
    properties:
      id:
        type: string
      rank:
        type: integer
      itemName:
        type: string
      itemImg:
        type: string
      parentId:
        type: string
      parentName:
        type: string
      itemDeclare:
        type: string
      isRoot:
        type: integer