swagger: "2.0"
info:
  description: "日升木业后台接口"
  version: "1.0.0"
  title: "sunup"
tags:
- name: "User"
  description: "用户相关接口"
- name: "ProjectLabel"
  description: "项目全局相关接口"
- name: "ProductItem"
  description: "商品分类相关接口"
- name: "ProjectOther"
  description: "其他相关接口"
- name: "Product"
  description: "商品相关接口"
- name: "ProjectNews"
  description: "新闻中心"
schemes:
- "http"
produces:
- "application/json"
securityDefinitions:
  token:
    type: apiKey
    name: Cookie
    in: header
security:
- token: []
paths:
  /project/email/sendMsg:
    post:
      tags:
        - "ProjectOther"
      summary: 发送邮件
      operationId: sendEmailMsg
      parameters:
        - in: body
          name: EmailMsgDTO
          schema:
            properties:
              title:
                type: string
                description: "标题"
              concent:
                type: string
                description: "内容"
              email:
                type: string
                description: "联系方式"
              code:
                type: string
                description: "代码"
      responses:
        200:
          description: "发送成功"

  /project/uploadImg:
    post:
      summary: 上传图片
      description: file：选择文件
      operationId: uploadImg
      tags:
        - "ProjectOther"
      consumes:
        - "multipart/form-data"
      produces:
        - "application/json"
      parameters:
        - in: formData
          name: file
          type: file
          required: true
      responses:
        '200':
          schema:
            type: string
          description: 返回图片地址



  /user/register:
    post:
      tags:
        - "User"
      summary : "注册用户"
      operationId: "registerUser"
      parameters:
        - name: "user"
          in:  body
          required: true
          schema:
            $ref: '#/definitions/UserDTO'
      responses:
        200:
          description: "success"
  /user/login:
    post:
      tags:
        - "User"
      summary: "用户登陆"
      operationId: "login"
      parameters:
        - name: "user"
          in:  body
          required: true
          schema:
            $ref: '#/definitions/UserDTO'
            required:
              - name
              - password
      responses:
        200:
          description: "success"
  /user/loginOut:
    get:
      tags:
        - "User"
      summary: "用户登出"
      operationId: "loginOut"
      responses:
        200:
          description: "success"

  /project/labels:
    get:
      tags:
        - "ProjectLabel"
      summary: "获取标签列表"
      operationId: "getLabel"
      parameters:
        - in: query
          name: id
          type: string
      responses:
        200:
          description: "success"
          schema:
            $ref: '#/definitions/LabelDTO'
    post:
      tags:
        - "ProjectLabel"
      summary: "添加标签"
      operationId: "addLabel"
      parameters:
        - name: "label"
          in:  body
          required: true
          schema:
            $ref: '#/definitions/LabelDTO'
            required:
              - name
              - labelCode
      responses:
          200:
            description: "success"
    delete:
      tags:
        - "ProjectLabel"
      summary: "删除标签"
      operationId: "deletedLable"
      parameters:
        - in: query
          name: "id"
          type: string
          required: true
      responses:
        200:
          description: "success"
    put:
      tags:
        - "ProjectLabel"
      summary: "修改标签"
      operationId: "modifyLabel"
      parameters:
        - name: "label"
          in:  body
          required: true
          schema:
            $ref: '#/definitions/LabelDTO'
            required:
              - name
              - id
      responses:
        200:
          description: "success"
  /project/labelList:
    get:
      tags:
        - "ProjectLabel"
      summary: "获取标签列表"
      operationId: "getLabels"
      parameters:
        - in: query
          name: "keyword"
          type: string
      responses:
        200:
          description: "success"
          schema:
            type: array
            items:
              $ref: '#/definitions/LabelDTO'


  /project/product/item:
    get:
      tags:
        - "ProductItem"
      summary: "查看分类内容"
      operationId: getItem
      parameters:
        - name: id
          in: query
          type: string
          description: "分类详情"
          required: true
      responses:
        '200':
          schema:
            $ref: '#/definitions/ItemDTO'
          description: "分类内容"
    post:
      tags:
        - "ProductItem"
      summary: "增加分类"
      operationId: addItem
      parameters:
        - name: "item"
          in: body
          required: true
          schema:
            $ref: '#/definitions/ItemDTO'
            required:
              - itemName
              - isRoot
      responses:
        '200':
          description: 新增成功
    put:
      tags:
        - "ProductItem"
      summary: "修改分类"
      operationId: modifyItem
      parameters:
        - name: "item"
          in: body
          required: true
          schema:
            $ref: '#/definitions/ItemDTO'
            required:
              - id
              - itemName
              - isRoot
      responses:
        '200':
          description: 修改成功
    delete:
      tags:
        - "ProductItem"
      summary: "删除分类"
      operationId: deletedItem
      parameters:
        - in: query
          name: id
          type: string
          required: true
          description: "分类ID"
      responses:
        200:
          description: "删除成功"
  /project/product/getRootItems:
    get:
      tags:
        - "ProductItem"
      summary: "获取根级分类"
      operationId: getRootItems
      responses:
        200:
          schema:
            type: array
            items:
              $ref: '#/definitions/ItemDTO'
          description: "获取主分类列表"
  /project/product/getItemsByParentId:
    get:
      tags:
        - "ProductItem"
      summary: "根据上级分类获取下级分类列表"
      operationId: getItemsByParentId
      parameters:
        - in: query
          name: parentId
          type: string
          required: true
      responses:
        200:
          schema:
            type: array
            items:
              $ref: '#/definitions/ItemDTO'
          description: "获取分类列表"
  /project/product/itemList:
    get:
      tags:
        - "ProductItem"
      summary: "查看分类列表"
      operationId: getItems
      parameters:
        - name: "key"
          in: query
          type: string
          description: "分类关键字，分类名，描述，模糊查询"
      responses:
        '200':
          schema:
            type: array
            items:
              $ref: '#/definitions/ItemDTO'
          description: "分类列表"
  /project/product/info:
    post:
      tags:
        - "Product"
      summary: "添加商品"
      operationId: addProductInfo
      parameters:
        - in: body
          name: productInfo
          required: true
          schema:
            $ref: '#/definitions/ProductDTO'
            required:
              - name
      responses:
        200:
          description: 添加成功
    delete:
      tags:
        - "Product"
      summary: 删除商品
      operationId: deleteProducts
      parameters:
        - in: query
          name: ids
          required: true
          type: array
          items:
            type: string
      responses:
        200:
          description: 删除成功
    put:
      tags:
        - "Product"
      summary: 修改商品信息
      operationId: modifyProductInfo
      parameters:
        - in: body
          name: productInfo
          schema:
            $ref: '#/definitions/ProductDTO'
            required:
              - id
              - name
          required: true
          description: id,name不能为空
      responses:
        200:
          description: 修改完成
    get:
      tags:
        - "Product"
      summary: "获取商品内容"
      operationId: getProductInfo
      parameters:
        - in: query
          name: id
          type: string
          required: true
      responses:
        200:
          schema:
            $ref: '#/definitions/ProductDTO'
          description: "商品"

  /project/product/queryList:
    get:
      tags:
        - "Product"
      summary: "获取商品列表"
      operationId: getProducts
      parameters:
        - in: query
          name: key
          type: string
        - in: query
          name: pageIndex
          type: integer
          description: 当前页数
          default: 0
        - in: query
          name: pageSize
          type: integer
          description: 页面大小
          default: 6
      responses:
        200:
          schema:
            type: array
            items:
              $ref: '#/definitions/ProductDTO'
          description: "商品列表"
  /project/product/listbyItem:
    get:
      tags:
        - "Product"
      summary: 获取分类下的所有商品
      operationId: queryListByItem
      parameters:
        - in: query
          name: pageIndex
          type: integer
          description: 当前页数
        - in: query
          name: pageSize
          type: integer
          description: 页面大小
        - in: query
          name: itemId
          type: string
          required: true
          description: 必填 分类ID
      responses:
        200:
          schema:
            type: array
            items:
              $ref: '#/definitions/ProductDTO'
          description: "商品列表"
  /project/product/listbyLabel:
    get:
      tags:
        - "Product"
      summary: 获取标签下的所有商品
      operationId: queryListByLabel
      parameters:
        - in: query
          name: pageIndex
          type: integer
          description: 当前页数
          default: 0
        - in: query
          name: pageSize
          type: integer
          description: 页面大小
          default: 6
        - in: query
          name: labelId
          type: string
          required: true
          description: 必填 标签ID
      responses:
        200:
          schema:
            type: array
            items:
              $ref: '#/definitions/ProductDTO'
          description: "商品列表"

  /project/product/listbyItemLabel:
    get:
      tags:
        - "Product"
      summary: 获取分类，标签下的所有商品
      operationId: queryListByItemLabel
      parameters:
        - in: query
          name: pageIndex
          type: integer
          description: 当前页数
          default: 0
        - in: query
          name: pageSize
          type: integer
          description: 页面大小
          default: 6
        - in: query
          name: labelId
          type: string
          description: 标签ID
        - in: query
          name: itemId
          type: string
          description: 分类ID
      responses:
        200:
          schema:
            type: array
            items:
              $ref: '#/definitions/ProductDTO'
          description: "商品列表"


  /project/center/news:
    post:
      summary: "添加新闻"
      operationId: addNews
      tags:
        - "ProjectNews"
      parameters:
        - in: body
          name: newsDto
          schema:
            $ref: '#/definitions/NewsDTO'
          required: true
      responses:
        200:
          description: "新增成功"
    delete:
      tags:
        - "ProjectNews"
      summary: "删除新闻"
      operationId: deleteByIds
      parameters:
        - in: query
          name: id
          type: string
          required: true
      responses:
        200:
          description: "删除成功"
    put:
      tags:
        - "ProjectNews"
      summary: "修改新闻"
      operationId: modifyNewsInfo
      parameters:
        - in: body
          name: newsDto
          schema:
            $ref: '#/definitions/NewsDTO'
          required: true
      responses:
        200:
          description: "修改成功"
    get:
      tags:
        - "ProjectNews"
      summary: "查看新闻内容"
      operationId: getNewsInfo
      parameters:
        - in: query
          name: id
          type: string
          required: true
      responses:
        200:
          schema:
            $ref: '#/definitions/NewsDTO'
          description: "新闻内容信息"

  /project/center/newsList:
    get:
      tags:
        - "ProjectNews"
      summary: "查看新闻内容"
      operationId: getNewsInfoList
      parameters:
        - in: query
          name: key
          type: string
        - in: query
          name: pageIndex
          type: integer
          description: 当前页数
          default: 0
        - in: query
          name: pageSize
          type: integer
          description: 页面大小
          default: 6
      responses:
        200:
          schema:
            type: array
            items:
              $ref: '#/definitions/NewsDTO'
          description: "新闻内容信息"


definitions:
  NewsDTO:
    type: object
    properties:
      id:
        type: string
      stye:
        type: string
        description: 新闻类型：1，公司新闻；2 行业新闻
      title:
        type: string
        description: 新闻标题
      intro:
        type: string
        description: 新闻简介
      author:
        type: string
        description: 作者
      back_img:
        type: string
        description: 背景图片
      subject:
        type: string
        description: 新闻内容
      createUser:
        type: string
      updateUser:
        type: string
      createTime:
        type: string
      updateTime:
        type: string


  ProductDTO:
    type: object
    properties:
      id:
        type: string
      type:
        type: string
        description: "商品类型：1 普通商品，2整装商品"
      name:
        type: string
        description: "商品名"
      price:
        type: string
        description: "价格"
      sales:
        type: string
        description: "销售量"
      amount:
        type: string
        description: "数量"
      measure:
        type: string
        description: "尺寸"
      texture:
        type: string
        description: "材质，当商品为整装时，为整体特色"
      productDeclare:
        type: string
        description: "商品描述"
      imgUrls:
        type: array
        items:
          type: string
        description: "图片列表"
      taobaoLink:
        type: string
        description: "淘宝链接"
      itemId:
        type: string
        description: "分类ID"
      labels:
        type: array
        items:
          type: string
        description: "标签列表"
      createUser:
        type: string
        description: "创建人"
      updateUser:
        type: string
        description: "更新人"
      createTime:
        type: string
        description: "创建时间"
      updateTime:
        type: string
        description: "更新时间"

  UserDTO:
    type: object
    properties:
      name:
        type: string
        description: "用户名"
      password:
        type: string
        description: "用户密码"

  LabelDTO:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
        description: "标签名"
      labelCode:
        type: string
        description: "标签代码，全系统唯一，且不可改"
      labelDeclare:
        type: string
        description: "描述标签"
      labelImg:
        type: string
        description: "标签图片，暂不使用"

  ItemDTO:
    type: object
    properties:
      id:
        type: string
      rank:
        type: integer
        description: "序号"
      itemName:
        type: string
        description: "分类名"
      itemImg:
        type: string
        description: "分类图片"
      parentId:
        type: string
        description: "上级分类ID"
      parentName:
        type: string
        description: "上级分类名"
      itemDeclare:
        type: string
        description: "分类描述"
      isRoot:
        type: integer
        description: "是否是一级分类"