server:
  port: 8080

spring:
  datasource:
    name: sunup
    url: jdbc:mysql://118.89.182.204:3306/sunup?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.chainof.sunup.model


#pagehelper分页插件配置
#  pagehelper.helperDialect=mysql
#  pagehelper.reasonable=true
#  pagehelper.supportMethodsArguments=true
#  pagehelper.params=count=countSql

logging:
  level:
    cn.chainof.sunup.common: DEBUG
    cn.chainof.sunup.conf: DEBUG
    cn.chainof.sunup.controller: INFO
    cn.chainof.sunup.mapper: DEBUG
    cn.chainof.sunup.filter: INFO
    cn.chainof.sunup.pojo: INFO
    cn.chainof.sunup.service: DEBUG