/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package cn.chainof.sunup.controller.api;

import org.springframework.core.io.Resource;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;

@Api(value = "File", description = "the File API")
public interface FileApi {

    @ApiOperation(value = "上传图片", nickname = "uploadImg", notes = "file：选择文件", response = String.class, authorizations = {
        @Authorization(value = "token")
    }, tags={ "File", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "返回图片地址", response = String.class) })
    @RequestMapping(value = "/project/uploadImg",
        produces = { "application/json" }, 
        consumes = { "multipart/form-data" },
        method = RequestMethod.POST)
    ResponseEntity<String> uploadImg(@ApiParam(value = "file detail") @Valid @RequestPart("file") MultipartFile file);

}
